# Generated by Django 4.2.1 on 2023-06-16 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_add_author', 'Can add author'), ('can_change_author', 'Can change author'), ('can_delete_author', 'Can delete author'), ('can_view_author', 'Can view author'))},
        ),
    ]
